# Generated by Django 5.0.6 on 2024-08-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [ migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('content', models.TextField()),
                ('author_id', models.IntegerField()),
                ('created_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
