# Generated by Django 5.0.6 on 2024-08-06 06:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commentss_postss_delete_comments_delete_posts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentss',
            new_name='Comments',
        ),
        migrations.RenameModel(
            old_name='Postss',
            new_name='Posts',
        ),
    ]
